/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import excecoes.PacienteInvalidoException;
import javax.swing.JOptionPane;
import modelo.Paciente;
import servicos.GestorAtendimento;

/**
 *
 * @author Edson
 */
public class DlgNovoPaciente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgNovoPaciente.class.getName());
    private GestorAtendimento gestorAtendimento;
    /**
     * Creates new form DlgNovoPaciente
     */
    public DlgNovoPaciente(java.awt.Frame parent, boolean modal, GestorAtendimento gestorAtendimento) {
        super(parent, modal);
        initComponents();
        this.gestorAtendimento = gestorAtendimento;
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNovoPaciente = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbIdade = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        btCancel = new javax.swing.JButton();
        btRegistar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Paciente");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        pnNovoPaciente.setBackground(new java.awt.Color(255, 255, 255));

        lbNome.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lbNome.setForeground(new java.awt.Color(0, 0, 0));
        lbNome.setText("Nome");

        txtNome.setBackground(new java.awt.Color(204, 204, 204));
        txtNome.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lbIdade.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lbIdade.setForeground(new java.awt.Color(0, 0, 0));
        lbIdade.setText("Idade");

        txtIdade.setBackground(new java.awt.Color(204, 204, 204));
        txtIdade.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });

        btCancel.setForeground(new java.awt.Color(0, 0, 0));
        btCancel.setText("Cancelar");
        btCancel.setBorder(null);
        btCancel.setBorderPainted(false);
        btCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancel.setFocusPainted(false);
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btRegistar.setBackground(new java.awt.Color(51, 51, 255));
        btRegistar.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btRegistar.setForeground(new java.awt.Color(255, 255, 255));
        btRegistar.setText("Registar");
        btRegistar.setBorder(null);
        btRegistar.setBorderPainted(false);
        btRegistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegistar.setFocusPainted(false);
        btRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistarActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout pnNovoPacienteLayout = new javax.swing.GroupLayout(pnNovoPaciente);
        pnNovoPaciente.setLayout(pnNovoPacienteLayout);
        pnNovoPacienteLayout.setHorizontalGroup(
            pnNovoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNovoPacienteLayout.createSequentialGroup()
                .addGroup(pnNovoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNovoPacienteLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pnNovoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIdade)
                            .addComponent(lbNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnNovoPacienteLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNovoPacienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        pnNovoPacienteLayout.setVerticalGroup(
            pnNovoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNovoPacienteLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnNovoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnNovoPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnNovoPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void btRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistarActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText().trim();
        String idadeString = txtIdade.getText().trim();
        
        if(nome.isEmpty() || idadeString.isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha o nome e a idade.", "Dados incompletos", JOptionPane.WARNING_MESSAGE);
             return;
        }
       
       int idade; 
        try {
            idade = Integer.parseInt(idadeString);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "A idade deve ser um numero inteiro.", "Idade Invalida", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            gestorAtendimento.registarPaciente(nome, idade);
            JOptionPane.showMessageDialog(this, "Paciente registado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (PacienteInvalidoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Paciente Invalido", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btRegistarActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
GestorAtendimento g = new GestorAtendimento();
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                DlgNovoPaciente dialog = new DlgNovoPaciente(new javax.swing.JFrame(), true, new GestorAtendimento());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btRegistar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbIdade;
    private javax.swing.JLabel lbNome;
    private javax.swing.JPanel pnNovoPaciente;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
